INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [29/Mar/2020 00:45:21] "[37mGET /empdb/employee HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [29/Mar/2020 00:45:21] "[37mGET /empdb/employee/101 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [29/Mar/2020 00:45:21] "[33mPOST /empdb/employee/ HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [29/Mar/2020 00:47:24] "[37mGET /empdb/employee HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [29/Mar/2020 00:47:24] "[37mGET /empdb/employee/101 HTTP/1.1[0m" 200 -
WARNING:server:azzooo
WARNING:server:None
ERROR:server:Exception on /empdb/employee [POST]
Traceback (most recent call last):
  File "/Users/andrea/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/andrea/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/andrea/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andrea/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/andrea/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 44, in createEmp
    'id':request.json['id'],
TypeError: 'NoneType' object has no attribute '__getitem__'
INFO:werkzeug:127.0.0.1 - - [29/Mar/2020 00:47:24] "[35m[1mPOST /empdb/employee HTTP/1.1[0m" 500 -
